# Generated by Django 4.2.18 on 2025-01-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='gift_wrap_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='warranty_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giftwrapdecorator',
            name='gift_wrap_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium'), ('luxury', 'Luxury')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='warrantydecorator',
            name='warranty_duration',
            field=models.IntegerField(choices=[(12, '12 months'), (24, '24 months'), (36, '36 months')], default=12),
        ),
    ]
