# Generated by Django 4.2.18 on 2025-01-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_cartproduct_gift_wrap_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='gift_wrap_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('premium', 'Premium'), ('luxury', 'Luxury')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='warranty_duration',
            field=models.IntegerField(blank=True, choices=[(12, '12 months'), (24, '24 months'), (36, '36 months')], null=True),
        ),
    ]
