# Generated by Django 4.2.18 on 2025-01-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_cartproduct_gift_wrap_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.shippingmethod'),
        ),
    ]
