# Generated by Django 4.2.18 on 2025-01-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_cart_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airshipping',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airshipping',
            name='shipping_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airshipping',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groundshipping',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groundshipping',
            name='shipping_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groundshipping',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
