# Generated by Django 4.2.18 on 2025-01-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_airshipping_shipping_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='gift_wrap_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('premium', 'Premium'), ('luxury', 'Luxury'), ('festival', 'Festival'), ('cartoon', 'Cartoon')], max_length=50, null=True),
        ),
    ]
