# Generated by Django 4.2.18 on 2025-01-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_cartproduct_gift_wrap_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='gift_wrap_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('premium', 'Premium'), ('luxury', 'Luxury')], max_length=50, null=True),
        ),
    ]
